apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: mcp-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: ghcr.io/mcp-ecosystem/mcp-gateway/apiserver:latest
        env:
        - name: ENV
          value: production
        - name: TZ
          value: UTC
        ports:
        - containerPort: 5234
        volumeMounts:
        - name: configs
          mountPath: /app/configs
        - name: data
          mountPath: /app/data
        - name: env-file
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: configs
        configMap:
          name: app-configs
      - name: data
        emptyDir: {}
      - name: env-file
        configMap:
          name: app-env
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: mcp-gateway
spec:
  ports:
  - port: 5234
    targetPort: 5234
  selector:
    app: apiserver