apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: mcp-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: localhost:8500/mcp-gateway-web:latest
        env:
        - name: TZ
          value: UTC
        ports:
        - containerPort: 80
        volumeMounts:
          - name: web-env
            mountPath: /app/.env
            subPath: .env
      volumes:
        - name: web-env
          configMap:
            name: web-env
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: mcp-gateway
spec:
  type: NodePort  # 或者使用 LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # 可选，指定节点端口
  selector:
    app: web