apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: mcp-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/mcp-ecosystem/mcp-gateway/web:latest
          env:
            - name: TZ
              value: UTC
            - name: ENV
              value: production
          ports:
            - containerPort: 80
            - containerPort: 5234
          volumeMounts:
            - name: web-env
              mountPath: /app/.env
              subPath: .env
            - name: configs
              mountPath: /app/configs
            - name: data
              mountPath: /app/data
      volumes:
        - name: web-env
          configMap:
            name: web-env
        - name: configs
          configMap:
            name: app-configs
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: mcp-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
    - port: 5234
      targetPort: 5234
      nodePort: 30081
  selector:
    app: web