name: "mock-stdio-svc"

routers:
  - server: "mock-stdio-svc"
    prefix: "/mcp/stdio"
    cors:
      allowOrigins:
        - "*"
      allowMethods:
        - "GET"
        - "POST"
        - "OPTIONS"
      allowHeaders:
        - "Content-Type"
        - "Authorization"
        - "Mcp-Session-Id"
      exposeHeaders:
        - "Mcp-Session-Id"
      allowCredentials: true

servers:
  - name: "mock-stdio-svc"
    namespace: "stdio-service"
    description: "Mock Stdio Service"

stdio_configs:
  - name: "amap-maps"
    command: "npx"
    args:
      - "-y"
      - "@amap/amap-maps-mcp-server"
    env:
      AMAP_MAPS_API_KEY: "{{.Args.AMAP_MAPS_API_KEY}}"
  - name: "github"
    command: "npx"
    args:
      - "-y"
      - "@github/github-mcp-server"
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: "{{.Args.GITHUB_PERSONAL_ACCESS_TOKEN}}"

sse_configs:
  - name: "web-search"
    url: "http://localhost:5236/web-search"