name: "mock-stdio-svc"
tenant: "default"

routers:
  - server: "mock-stdio-svc"
    prefix: "/mcp/stdio-service/amap-maps"
    cors:
      allowOrigins:
        - "*"
      allowMethods:
        - "GET"
        - "POST"
        - "OPTIONS"
      allowHeaders:
        - "Content-Type"
        - "Authorization"
        - "Mcp-Session-Id"
      exposeHeaders:
        - "Mcp-Session-Id"
      allowCredentials: true

servers:
  - name: "mock-stdio-svc"
    namespace: "stdio-service"
    description: "Mock Stdio Service"

stdio_server:
  name: "amap-maps"
  command: "npx"
  args:
    - "-y"
    - "@amap/amap-maps-mcp-server"
  env:
    AMAP_MAPS_API_KEY: "{{.Request.Headers.Apikey}}"

sse_server:
  name: "web-search"
  url: "http://localhost:5236/web-search"